name: Cameraplugin
description: A description of your plugin
version: 1.0.0
author: Mohammed Thoufiq
homepage: https://github.com/your_username/your_plugin
repository: https://github.com/your_username/your_plugin
publish_to: 'none' # Remove this line when you're ready to publish

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
